### ISSUE TITLE
Change period for Bluetooth and link data types

### ISSUE THREAD

**Issue by rcavaliere** [ilvalle/w2panalytics#22]
Traffic data, including Bluetooth and Link data, must be available in only three different periods: (i) 900 [s], as it is (15 [minutes]); (ii) 3600 [s](1 [hour]), 1440 [s](12 [hours]). The latter two will substitute existing periods of 1800 [s] and 21600 [s](Bluetooth); 1800 [s], 7200 [s] and 21600 [s](Link). Historical values should be computed and stored as well, so that they can be used for future evaluation studies.

**Comment by alessiovaralta** [comment]
Now in the map the period is ':'1800'. I change this value with 1440?
